name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start the server with '...'
        2. Send request to '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - Node.js version: [e.g. 20.10.0]
        - Package version: [e.g. 1.0.0]
        - MCP Client: [e.g. Claude Desktop, MCP Inspector]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please copy and paste any relevant log output or error messages
      render: shell
      placeholder: Paste logs here...

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share relevant configuration (remove sensitive data)
      render: json
      placeholder: |
        {
          "mcpServers": {
            "activitypub": {
              "command": "npx",
              "args": ["-y", "activitypub-mcp-server"]
            }
          }
        }

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I am using a supported Node.js version (18+)
          required: true
