import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// The favicon / app-icon set is committed (generated by scripts/generate-favicons.js,
// not built on deploy). Guard that the full set exists and that the manifest's
// relative icon srcs resolve to real files in public/ — a misplaced output or a
// renamed icon would otherwise 404 silently in browsers / fail PWA install.

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const publicDir = join(repoRoot, "public");

const REQUIRED_ICONS = [
  "favicon.svg",
  "favicon.ico",
  "apple-touch-icon.png",
  "icon-192.png",
  "icon-512.png",
  "icon-512-maskable.png",
  "manifest.webmanifest",
];

describe("public icon set is complete", () => {
  for (const name of REQUIRED_ICONS) {
    it(`${name} exists in public/`, () => {
      expect(existsSync(join(publicDir, name)), `missing public/${name}`).toBe(true);
    });
  }

  it("favicon.ico is a valid ICO (type=1) with at least one image", () => {
    const ico = readFileSync(join(publicDir, "favicon.ico"));
    expect(ico.readUInt16LE(0)).toBe(0); // reserved
    expect(ico.readUInt16LE(2)).toBe(1); // type 1 = icon
    expect(ico.readUInt16LE(4)).toBeGreaterThan(0); // image count
  });

  it("manifest is valid JSON and every icon src resolves to a file in public/", () => {
    const manifest = JSON.parse(readFileSync(join(publicDir, "manifest.webmanifest"), "utf8"));
    expect(Array.isArray(manifest.icons)).toBe(true);
    for (const icon of manifest.icons) {
      // srcs are relative (resolve against the manifest URL under the base path),
      // so they map directly to a file in public/.
      expect(existsSync(join(publicDir, icon.src)), `manifest icon missing: ${icon.src}`).toBe(
        true,
      );
    }
    // A maskable icon and at least one "any" icon must be present (PWA installability).
    const purposes = manifest.icons.flatMap((i: { purpose?: string }) =>
      (i.purpose ?? "any").split(" "),
    );
    expect(purposes).toContain("any");
    expect(purposes).toContain("maskable");
  });
});
